# Build Stage
FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_API_TARGET
ARG VITE_FRAPPE_TARGET
ENV VITE_API_TARGET=$VITE_API_TARGET
ENV VITE_FRAPPE_TARGET=$VITE_FRAPPE_TARGET

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Serve Stage
FROM nginx:alpine

# Copy built assets from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx config for React Router (SPA) handling
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
