"""add_image_url_to_landparcel

Revision ID: 2e22e7d50490
Revises: d4974a925af6
Create Date: 2025-12-05 11:53:19.846720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e22e7d50490'
down_revision = 'd4974a925af6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landparcel', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landparcel', 'image_url')
    # ### end Alembic commands ###
