"""Initial tables

Revision ID: 76c9dfa9c06f
Revises: 
Create Date: 2025-12-03 13:08:30.812308

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '76c9dfa9c06f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landparcel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('village_id', sa.String(), nullable=True),
    sa.Column('khasra_number', sa.String(), nullable=True),
    sa.Column('area_text', sa.String(), nullable=True),
    sa.Column('area_geom', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landparcel_khasra_number'), 'landparcel', ['khasra_number'], unique=False)
    op.create_index(op.f('ix_landparcel_village_id'), 'landparcel', ['village_id'], unique=False)
    op.create_table('mutation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('parties', sa.JSON(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('effect', sa.String(), nullable=True),
    sa.Column('document_ref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_urdu', sa.String(), nullable=True),
    sa.Column('name_english', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('consent_flags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provenance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('source_doc_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provenance_entity_id'), 'provenance', ['entity_id'], unique=False)
    op.create_table('cultivation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('crop_code', sa.String(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('irrigation', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['landparcel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('rights_type', sa.String(), nullable=True),
    sa.Column('share', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['landparcel.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vghmap',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('village_code', sa.String(), nullable=True),
    sa.Column('halqa_code', sa.String(), nullable=True),
    sa.Column('girdawari_code', sa.String(), nullable=True),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['landparcel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vghmap_girdawari_code'), 'vghmap', ['girdawari_code'], unique=False)
    op.create_index(op.f('ix_vghmap_halqa_code'), 'vghmap', ['halqa_code'], unique=False)
    op.create_index(op.f('ix_vghmap_village_code'), 'vghmap', ['village_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vghmap_village_code'), table_name='vghmap')
    op.drop_index(op.f('ix_vghmap_halqa_code'), table_name='vghmap')
    op.drop_index(op.f('ix_vghmap_girdawari_code'), table_name='vghmap')
    op.drop_table('vghmap')
    op.drop_table('tenure')
    op.drop_table('cultivation')
    op.drop_index(op.f('ix_provenance_entity_id'), table_name='provenance')
    op.drop_table('provenance')
    op.drop_table('person')
    op.drop_table('mutation')
    op.drop_index(op.f('ix_landparcel_village_id'), table_name='landparcel')
    op.drop_index(op.f('ix_landparcel_khasra_number'), table_name='landparcel')
    op.drop_table('landparcel')
    op.drop_table('claim')
    # ### end Alembic commands ###
