"""Add ReviewTask Table

Revision ID: 881e4d044162
Revises: 903113ce093f
Create Date: 2025-12-04 11:36:25.146967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881e4d044162'
down_revision = '903113ce093f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_document_id'), 'review_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_id'), 'review_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_tasks_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_document_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    # ### end Alembic commands ###
