"""Add ReviewTask

Revision ID: 903113ce093f
Revises: 76c9dfa9c06f
Create Date: 2025-12-04 11:33:03.605408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903113ce093f'
down_revision = '76c9dfa9c06f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
