"""add_person_demographics

Revision ID: b29bca7b1d09
Revises: 6b0b221727c6
Create Date: 2025-12-14 10:31:34.976180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b29bca7b1d09'
down_revision = '6b0b221727c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landparcel', sa.Column('landmark', sa.String(), nullable=True))
    # op.alter_column('landparcel', 'parcel_id', existing_type=sa.VARCHAR(length=14), nullable=False) # Skip strict constraint for now
    op.add_column('person', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('person', sa.Column('father_name', sa.String(), nullable=True))
    op.add_column('person', sa.Column('address', sa.String(), nullable=True))
    op.add_column('person', sa.Column('district', sa.String(), nullable=True))
    op.add_column('person', sa.Column('village', sa.String(), nullable=True))
    op.create_index(op.f('ix_person_district'), 'person', ['district'], unique=False)
    op.create_index(op.f('ix_person_village'), 'person', ['village'], unique=False)
    # op.drop_column('person', 'aadhaar_verified') # Keep it
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('aadhaar_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_person_village'), table_name='person')
    op.drop_index(op.f('ix_person_district'), table_name='person')
    op.drop_column('person', 'village')
    op.drop_column('person', 'district')
    op.drop_column('person', 'address')
    op.drop_column('person', 'father_name')
    op.drop_column('person', 'first_name')
    op.alter_column('landparcel', 'parcel_id',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    op.drop_column('landparcel', 'landmark')
    op.create_table('record_of_rights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('ulpin', sa.VARCHAR(length=14), autoincrement=False, nullable=True),
    sa.Column('ror_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('khewat_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('khatoni_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('khasra_numbers', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('owner_names', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue_village', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tehsil', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('record_of_rights_pkey')),
    sa.UniqueConstraint('ror_number', name=op.f('record_of_rights_ror_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('aadhaar_consent',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('farmer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('aadhaar_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('aadhaar_last_4', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('consent_given', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('consent_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('consent_purpose', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('consent_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('aadhaar_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('aadhaar_verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('aadhaar_consent_pkey'))
    )
    op.create_index(op.f('ix_aadhaar_hash'), 'aadhaar_consent', ['aadhaar_hash'], unique=False)
    op.create_index(op.f('ix_aadhaar_farmer'), 'aadhaar_consent', ['farmer_id'], unique=False)
    op.create_table('ulpin_farmer_ror_link',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('ulpin', sa.VARCHAR(length=14), autoincrement=False, nullable=True),
    sa.Column('farmer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ror_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ownership_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ownership_share', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('validated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('validated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('validated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ulpin_farmer_ror_link_pkey')),
    sa.UniqueConstraint('farmer_id', 'ror_id', 'ulpin', name=op.f('ulpin_farmer_ror_link_farmer_id_ror_id_ulpin_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_link_validated'), 'ulpin_farmer_ror_link', ['validated'], unique=False)
    op.create_index(op.f('ix_link_ulpin'), 'ulpin_farmer_ror_link', ['ulpin'], unique=False)
    op.create_index(op.f('ix_link_farmer'), 'ulpin_farmer_ror_link', ['farmer_id'], unique=False)
    # ### end Alembic commands ###
