#!/bin/bash

echo "=============================================="
echo "🚀 DEVELOPMENT SERVER - STATUS"
echo "=============================================="
echo ""
echo "Started: $(date)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 BACKEND SERVICES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null | head -15

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 KEYCLOAK SSO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Admin Console: http://localhost:8080/admin"
echo "Username: admin"
echo "Password: admin"
echo ""
echo "Realm: agristack"
echo "Mobile Client: agristack-mobile"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🖥️  BACKEND API"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "API Endpoint: http://localhost:80/api/v1"
echo "Direct Backend: http://localhost:8000"
echo ""

# Test backend
PARCELS=$(curl -s http://localhost:80/api/v1/parcels/ 2>/dev/null | jq '. | length' 2>/dev/null || echo "?")
echo "Database: $PARCELS parcels available"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 MOBILE APP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if Metro is running
if pgrep -f "expo start" > /dev/null; then
    echo "✅ Metro Bundler: RUNNING"
    echo "✅ Expo Dev Server: http://localhost:8081"
    echo ""
    echo "Expo Go URL: exp://192.168.1.11:8081"
    echo "Web: http://localhost:8081"
else
    echo "⚠️  Metro Bundler: Not running"
    echo "Start with: cd mobile && npx expo start"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 MONITORING & TOOLS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Prometheus: http://localhost:9090"
echo "Grafana: http://localhost:3000"
echo "Frappe: http://localhost:8001"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 QUICK START GUIDE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. MOBILE APP (Expo Go)"
echo "   • Open Expo Go on your phone"
echo "   • Scan QR code from Metro terminal"
echo "   • OR use simulator:"
echo "     npx expo start"
echo "     Press 'i' for iOS simulator"
echo ""
echo "2. LOGIN"
echo "   • Tap 'Sign in with Keycloak'"
echo "   • Username: admin"
echo "   • Password: admin"
echo ""
echo "3. FEATURES"
echo "   • Map View (fallback in Expo Go)"
echo "   • Add Parcel"
echo "   • Camera (mock in Expo Go)"
echo "   • Data Sync"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 USEFUL COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "View logs:"
echo "  docker logs land_records_backend -f"
echo "  docker logs land_records_keycloak -f"
echo ""
echo "Restart services:"
echo "  docker-compose restart backend"
echo "  docker-compose restart keycloak"
echo ""
echo "Stop all:"
echo "  docker-compose down"
echo "  pkill -f 'expo start'"
echo ""
echo "Check status:"
echo "  docker ps"
echo "  curl http://localhost:80/api/v1/parcels/"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ ALL SERVICES RUNNING!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Ready for development! 🚀"
echo ""
echo "=============================================="
